# Site settings
title: Abhischreiben
description: Abhischreiben where thoughts becomes actions.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Abhischreiben
user_description: A Online memory space where everything is conceived in a different perspective.
In other words, experiencing the world with eccentricity.
In the end, it's either 0 or 1.
email: abhijithremesh@gmail.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
